### ISSUE TITLE
cant edit displayed commands

### ISSUE THREAD

**Issue by maxi0033** [respawner/looking-glass#100]
"The documentation configuration can also be used to disable commands by setting the title of the command to null."

i added following to config.php:
$config['doc']['bgp']['command'] = null;
$config['doc']['as-path-regex']['command'] = null;
$config['doc']['as']['command'] = null;
$config['doc']['ping']['command'] = null;

but nothing has changed. the commands are still be displayed at the website. i am using release 2.0.1.

**Comment by respawner** [comment]
The whole command array should be nullified not just the `command` item.

```php
$config['doc']['bgp'] = null;
$config['doc']['as-path-regex'] = null;
$config['doc']['as'] = null;
$config['doc']['ping'] = null;
$config['doc']['traceroute'] = null;
```

**Comment by maxi0033** [comment]
still no change to the displayed output on the website. the commands are still available.
i also cleared my cache and tryed it in private browser.

**Comment by vincentbernat** [comment]
This does not work with 2.0.1. You need to use master.
