### ISSUE TITLE
arista error at each call

### ISSUE THREAD

**Issue by maxi0033** [respawner/looking-glass#101]
[Mon Jan 27 12:30:30.] [:error] [pid xy] [client 1.2.3.4:37538] PHP Fatal error:  Non-abstract method Arista::build_bgp() must contain body in /var/www/xyz/routers/arista.php on line 27, referer: http://xyzsite.net/

**Comment by respawner** [comment]
What version of PHP are you using?

**Comment by maxi0033** [comment]
PHP Version 5.6.40-0+deb8u7

**Comment by respawner** [comment]
You need at least PHP 7 to be able to use version 2.x (or git) of this looking glass. If you can't upgrade PHP on your install, use version 1.x of the looking glass.
