### ISSUE TITLE
Wont work out of the box for VyOS 1.2.0 or later

### ISSUE THREAD

**Issue by harajukakei** [respawner/looking-glass#102]
Anybody having issues with VyOS here ? Seems every command doesnt match with VyOS 1.2.0 or later. Willing to help, but where i can start to modfiy it ?

**Comment by respawner** [comment]
The VyOS support was introduced with `routers/vyatta.php` which is based on `routers/quagga.php`.
You might want to create a dedicated file and class for VyOS in the `routers/` directory.

**Comment by harajukakei** [comment]
ok, i'll try.

**Comment by echodreamz** [comment]
@harajukakei were you able to get this working properly?
