### ISSUE TITLE
Any command cause error No parameter given.

### ISSUE THREAD

**Issue by pyros13** [respawner/looking-glass#104]
Hi have this error:
Error! No parameter given.
Cloned git 2 days ago.

Router is Cisco 7600 classic IOS
I can see that server connecting to router successfully, but looks like no command send to router actually.

PHP 7.2.11 (cli) (built: Oct  9 2018 15:09:36) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.11, Copyright (c) 1999-2018, by Zend Technologies

In log 
[2020-02-10 11:06:04] [client: xx.xx.xx.xx] xx.xx.44.45 > [BEGIN]  show bgp ipv4 unicast 188.43.242.42
[2020-02-10 11:06:04] [client: xx.xx.xx.xx] xx.xx.44.45 > [END]  show bgp ipv4 unicast 188.43.242.42

php error log
PHP Notice:  Undefined variable: displayable in /var/www/html/looking-glass/routers/router.php on line 102

![Capture](https://user-images.githubusercontent.com/5909385/74145128-252abe00-4c0f-11ea-9cdd-1be4800548fc.PNG)

[Config.txt](https://github.com/respawner/looking-glass/files/4180444/Config.txt)

**Comment by pyros13** [comment]
Some add to this issue, while trying to solve this, i've found out that, telnet as connection give this error. But using SSH is ok. So you need to check if telnet is still an option for connection.

**Comment by respawner** [comment]
I strongly advise to use SSH instead of telnet. Not all routers do not work in the same way. So I'm thinking about removing telnet support in a next major release or allow the user to customize the behavior of the telnet code (such as carriage return code, ...).

**Comment by respawner** [comment]
Telnet code is to be deprecated soon. If you use telnet in 2021 you're probably doing something wrong :D
