### ISSUE TITLE
ADD Huawei Router Support

### ISSUE THREAD

**Issue by ajcorrea** [respawner/looking-glass#111]
https://pastebin.com/yiQE1d1i

Here´s routers/huawei.php

**Comment by ajcorrea** [comment]
https://pastebin.com/yiQE1d1i

**Comment by ajcorrea** [comment]
diff -Nur html3/routers/router.php html2/routers/router.php
--- html3/routers/router.php    2020-04-06 01:48:26.684773037 -0300
+++ html2/routers/router.php    2020-04-06 00:43:48.864870814 -0300
@@ -33,6 +33,7 @@
 require_once('quagga.php');
 require_once('frr.php');
 require_once('vyatta.php');
+require_once('huawei.php');
 require_once('includes/utils.php');
 require_once('auth/authentication.php');

@@ -235,6 +236,9 @@
       case 'ios':
         return new Cisco($config, $router_config, $id, $requester);

+      case 'huawei':
+       return new Huawei($config, $router_config, $id, $requester);
+
       case 'extreme_netiron':
         return new ExtremeNetIron($config, $router_config, $id, $requester);

**Comment by respawner** [comment]
Cqn you submit the changes as a pull request? It will be easier for me to review the changes and merge them once approved.

**Comment by ajcorrea** [comment]
Done..
