### ISSUE TITLE
Connection closed prematurely in libs/phpseclib-2.0.27/Net/SSH2.php on line 3934

### ISSUE THREAD

**Issue by yapjackson** [respawner/looking-glass#118]
Any idea how to fix this?

Every ping will return this error in the PHP Log.

PHP Notice:  Connection closed prematurely in libs/phpseclib-2.0.27/Net/SSH2.php on line 3934

**Comment by respawner** [comment]
It seems like a library version issue. Did you try with another version of it?

**Comment by makanbaks0** [comment]
PHP Notice:  Connection closed prematurely in /libs/phpseclib-2.0.23/Net/SSH2.php on line 3901

I got this last week, I want to change the library, but cant find anything from config.php, please help..

**Comment by respawner** [comment]
phpseclib updated to 2.0.30, issue closed for now, please reopen it if the issue persist with phpseclib 2.0.30.
