### ISSUE TITLE
Source addresses for ping and traceroute on Mikrotik OS

### ISSUE THREAD

**Issue by jonathaanbastin** [respawner/looking-glass#120]
Very sorry I am not a dev so my method is a little crude hence no committing code myself.

for show route on Mikrotik the command is better being:
 ip route print detail where dst-address=

Code change I am suggesting:

€‹    if (match_ipv6($parameter, false)) {
      $cmd->add('ipv6');
    } else if (match_ipv4($parameter, false)) {
      $cmd->add('ip');
    }
    $cmd->add('route print detail'); //Changed from $cmd->add('route print');

I am finding specifying interface fails on traceroute and scr-address is better but that is my finding. Looking at the code I adjusted to:
    if ($this->get_source_interface_id('ipv4')) {
      $cmd->add('src-address='.$this->get_source_interface_id('ipv4'));
    }

and updated the config to:
$config['routers']['router1']['source-interface-id']['ipv4'] = 

However, with my very limited knowledge, I didn't know how to leave the code in if you left the ['ipv4'] to switch back to the interface. As such I have no code to suggest to complete that puzzle.

**Comment by respawner** [comment]
To enable details for route printing you can set the following configuration to `true`.

```php
$config['routers']['router1']['bgp_detail'] = true;
```

As for the source interface it depends on the router itself. You can just remove this setting from your configuration if you don't want to use it. If your router expect an interface name then just set it like so:

```php
$config['routers']['router1']['source-interface-id'] = 'lo0';
```

However if your router expects IP addresses, use the following settings:

```php
$config['routers']['router1']['source-interface-id']['ipv6'] = '2001:db8::1';
$config['routers']['router1']['source-interface-id']['ipv4'] = '192.168.1.1';
```

All of this is documented [here](https://looking-glass.readthedocs.io/en/latest/configuration/).

**Comment by jonathaanbastin** [comment]
OK agreed I missed the BGP detail. However looking at the code for Mikrotik there is no code to allow src-address only interface.

**Comment by respawner** [comment]
Can you give us the command for the src-address as you would like to use it?

**Comment by jonathaanbastin** [comment]
tool traceroute count=1 use-dns=yes src-address= xx.xx.xx.xx

I have made it work by updating the mikrotik.php to:

    if ($this->has_source_interface_id('ipv4')) {
      $cmd->add('src-address='.$this->get_source_interface_id('ipv4'));
    }

instead of:

  if ($this->get_source_interface_id()) {
      $cmd->add('interface='.$this->get_source_interface_id());
    }

**Comment by respawner** [comment]
Thanks, we'll try to implement this ASAP.

**Comment by jonathaanbastin** [comment]
Cool thanks. I would put the code in and try to give back to the project but you wouldn't want my code with the level I am at.
