### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by pasan1986** [respawner/looking-glass#121]
Hi,

I receive following error when run looking glass, please help me to fix this issue.
[Fri Jun 26 16:51:02.343718 2020] [php7:warn] [pid 25668] [client x.x.x.x:52683] PHP Warning:  file_put_contents(/var/log/looking-glass.log): failed to open stream: Permission denied in /var/www/html/looking_new/includes/utils.php on line 353, referer: http://192.168.3.3:8080/

Thanks

**Comment by rabin-io** [comment]
Change the owner of the log file to be the same as the web server or the php-fpm (so basically it depends on how you run the application), if you in a hurry and just want to be done with it, change the path to something like '/tmp/lg.log'.

```
# as root / on debian system with apache/httpd
# on CentOS the user it httpd IIRC (look it up with running ps)
touch /var/log/looking-glass.log
chown apache /var/log/looking-glass.log
```
