### ISSUE TITLE
 PHP Fatal error

### ISSUE THREAD

**Issue by pasan1986** [respawner/looking-glass#122]
Hi,

Im getting an error as below, please help me to fix this

[Mon Jun 29 10:14:40.185785 2020] [php7:error] [pid 9016] [client 203.94.65.85:51257] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/www/html/looking_new/auth/telnet.php on line 59, referer: http://192.168.3.3:8080/

Thanks

**Comment by rabin-io** [comment]
Probably your machine (the one running `lg`) can't `telnet` to the host (packet are drop?), PHP have max execution time, which kick in before the telnet script is getting timed out.
