### ISSUE TITLE
Traceroute - Access to this resource on the server is denied!

### ISSUE THREAD

**Issue by SamMNC** [respawner/looking-glass#133]
Hey,

I keep having this (below) error show up on the traceroute option. All other options are fine.
Any Ideas?

Error! <!DOCTYPE html> <html style="height:100%"> <head> <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" > <title> 403 Forbidden </title></head> <body style="color: #444; margin:0;font: normal 14px/20px Arial, Helvetica, sans-serif; height:100%; background-color: #fff;"> <div style="height:auto; min-height:100%; "> <div style="text-align: center; width:800px; margin-left: -400px; position:absolute; top: 30%; left:50%;"> <h1 style="margin:0; font-size:150px; line-height:150px; font-weight:bold;">403</h1> <h2 style="margin-top:20px;font-size: 30px;">Forbidden </h2> <p>Access to this resource on the server is denied!</p> </div></div></body></html>

**Comment by respawner** [comment]
Looks like a web server issue, not a looking glass one.

**Comment by dpskipper** [comment]
I can confirm that this issue occurs on lightspeed webservers. A solution that worked for me was to disable mod_security in .htaccess

```
<IfModule mod_security.c>
  SecFilterEngine Off
  SecFilterScanPOST Off
</IfModule>
```
