### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by kotviphp** [respawner/looking-glass#135]
Hello
how to add a logo?
which directory?

**Comment by respawner** [comment]
Where ever you want as long as your webserver can read the file.

```php
$config['frontpage']['image'] = null;
```

You can take a look at the [documentation](https://looking-glass.readthedocs.io/en/latest/configuration/).

**Comment by kotviphp** [comment]
logo not displayed
![logo](https://user-images.githubusercontent.com/25497579/92121513-2e35e380-ee1c-11ea-8663-32ff8f0f8315.JPG)

**Comment by respawner** [comment]
Did you made sure that the path and file used for `$config['frontpage']['image']` are readable by your web server? Read-only access should be enough.

**Comment by kotviphp** [comment]
yes? full access

**Comment by respawner** [comment]
Can you paste the relevant block of configuration and logs from your web server that says you cannot have access to the logo?

**Comment by kotviphp** [comment]
where to check?

**Comment by respawner** [comment]
Only you can know that. It depends on your web server configuration and operating system.
