### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by kotviphp** [respawner/looking-glass#136]
Hello
when I enter any command

Error! Unknown authentication mechanism "ssh-password"."
through the terminal, connect  is access

**Comment by respawner** [comment]
Can you provide your configuration file content without the sensitive data?

**Comment by kotviphp** [comment]
$config['routers']['router1']['host'] = 'x.x.x.x';
// The user to use to connect to the router
$config['routers']['router1']['user'] = 'LookingGlass';
// The password of the given user
$config['routers']['router1']['pass'] = 'password';
// The authentication mechanism to use (can be ssh-password or telnet)
$config['routers']['router1']['auth'] = 'password';
// The router type (can be cisco, ios, juniper or junos)
$config['routers']['router1']['type'] = 'Nokia';
// The router source interface to be used
$config['routers']['router1']['source-interface-id'] = 'lo0';
// The router description to be displayed in the router list
$config['routers']['router1']['desc'] = 'hostname';

**Comment by respawner** [comment]
The line `$config['routers']['router1']['auth'] = 'password';` should be `$config['routers']['router1']['auth'] = 'ssh-password';`

**Comment by kotviphp** [comment]
$config['routers']['router1']['host'] = '172.23.30.228';
// The user to use to connect to the router
$config['routers']['router1']['user'] = 'LookingGlass';
// The password of the given user
$config['routers']['router1']['pass'] ='user password';
// The authentication mechanism to use (can be ssh-password or telnet)
$config['routers']['router1']['auth'] = 'my ssh-password';
// The router type (can be cisco, ios, juniper or junos)
$config['routers']['router1']['type'] = 'Nokia';
// The router source interface to be used
$config['routers']['router1']['source-interface-id'] = 'lo0';
// The router description to be displayed in the router list
$config['routers']['router1']['desc'] = 'MY HOSTNAME';

Error! Unknown authentication mechanism "my ssh-password"."

**Comment by respawner** [comment]
`$config['routers']['router1']['auth']` should be set to `ssh-password`, the value is `ssh-password`. The actual password must be provided with `$config['routers']['router1']['pass']`.

In the [doc](https://looking-glass.readthedocs.io/en/latest/configuration/) look for `SSH with Password` with to view an example.

**Comment by kotviphp** [comment]
Please explain what the password is here

$config['routers']['router1']['pass'] ='user password';

**Comment by respawner** [comment]
This is where you have to set the password used by SSH to connect to the device.

**Comment by kotviphp** [comment]
thank
