### ISSUE TITLE
Error! Cannot connect to router.

### ISSUE THREAD

**Issue by hendranata** [respawner/looking-glass#142]
helo

i have make sure that config.php already set properly for router1.
but after try and error seems does not work with message: Error! Cannot connect to router.

i have tried enable error log: 
$config['logs']['file'] = '/var/log/looking-glass.log';
$config['logs']['format'] = '[%D] [client: %R] %H > %C';
$config['logs']['auth_debug'] = true;

but cant find those error log..
any idea?
i have make sure that i am able to connect the router using user, pass, ssh auth from that server without any issue.
but why looking glass said "can not connect to router"

**Comment by hendranata** [comment]
[Mon Oct 26 09:35:36.354781 2020] [php7:notice] [pid 18096] [client 36.81.174.4:57076] PHP Notice:  Cannot connect to 10.xx.xx.1:22. Error 111. Connection refused in /opt/looking-glass/libs/phpseclib-1.0.14/Net/SSH2.php on line 1174, referer: http://lg.xxxx.id/

seems ssh port 22 is wrong.. how do we set ssh port in config.php ?

**Comment by respawner** [comment]
Make sure the file is created and writable by your web server user.
