### ISSUE TITLE
Having difficulty with IPv6 BIRD router commands

### ISSUE THREAD

**Issue by strahinjalalic** [respawner/looking-glass#144]
When I try to send request either for BGP table. regex or ASN for BIRD router i get following output: **bash: birdc6: command not found**

Am I missing some settings for IPv6?

**Comment by respawner** [comment]
If you are using BIRD 2.0 `birdc6` does not exist anymore. The quick and dirty fix is to created a symlink `birdc6` pointing to `birdc`. But this should be fixed in the looking glass too by knowing the BIRD version.

**Comment by strahinjalalic** [comment]
I managed to solve that, thanks.
