### ISSUE TITLE
PHP Notice:  Expected SSH_MSG_KEXINIT

### ISSUE THREAD

**Issue by fabifri** [respawner/looking-glass#21]
Hi folks,

first of all - thanks for providing this nicely done looking-glass. Sadly, i can't get it to run on our systems...
I tried to install the looking-glass on a fresh install of Debian9+Apache2+PHP7 (nothing special, just all default config), cloned the files into /var/www/html and adjusted the config.php for our cisco routers.
However, i cannot get connected to them and run into the configured timeout.

**I get the following error message on the apache error.log:**
> PHP Notice:  Expected SSH_MSG_KEXINIT in /var/www/html/libs/phpseclib-1.0.7/Net/SSH2.php on line 1131

**On the log of our router i can see the SSH connection comming in, because our ACL allows the connect:**
> %SEC-6-IPACCESSLOGP: list ssh permitted tcp xx.xx.xx.xx(53449) -> 0.0.0.0(22), 1 packet

I tried to manually connect with my readonly-user to the router via ssh and it works just fine.

Two things i already tried:
- running the provided docker-container - can also not connect to the router (timeout)
- swapping out the phpseclib-1.0.7 with phpseclib version 2 - breaks everything. ;-)

As i am not really a linux professional nor php programmer, i don't know where to look at the moment.

kind regards
Fabian

**Comment by respawner** [comment]
I tried to reproduce the issue but I did not manage to do it.
I just had to install the following packages and it just worked:

> apt install apache2 libapache2-mod-php7.0 php7.0-xml

Then git clone everything, config, and magic (with SSH password and SSH key based authentication).
Can you maybe share your config file (without sensitive data)?

**Comment by respawner** [comment]
@fabifri do you still have the issue?

**Comment by yolabingo** [comment]
I got this error while trying to use a phpseclib script to connect to a Gentoo linux server with default sshd_config settings. 
Unlike Debian/Ubuntu, Gentoo sshd_config defaults include
```
# To disable tunneled clear text passwords, change to no here! 
PasswordAuthentication no
ChallengeResponseAuthentication yes
```
Changing the Gentoo sshd_config to match Debian defaults:
```
PasswordAuthentication yes
ChallengeResponseAuthentication no
```
allows the phpseclib to connect.

I have no idea if there is a nob for that setting in your Cisco.
