### ISSUE TITLE
Docker image is outdated

### ISSUE THREAD

**Issue by schadom** [respawner/looking-glass#46]
When pulling the docker image `gmazoyer/looking-glass:latest` from DockerHub I get version 1.3.0 instead of the current master branch from Github. Could the image be updated to pull the latest version from Github?

See 
https://hub.docker.com/r/gmazoyer/looking-glass/
https://microbadger.com/images/gmazoyer/looking-glass

Thanks in advance

**Comment by respawner** [comment]
Fixed in 35dbad2.
