### ISSUE TITLE
Make .* and variants invalid regexp

### ISSUE THREAD

**Issue by jlixfeld** [respawner/looking-glass#53]
If a user decides to expose the regexp command, permitting variants of `.*` could be used as an attack vector against the router control plane since it will essentially try to dump the entire routing table and consume lots of CPU in the process.

I'm not very versed in php, but looking at the code, I think creating an additional filter in `match_aspath_regex()` would be a reasonable mitigation?

These are some examples of bad regexp:

`.`
`.*`
`.[,]*`
`.[0-9,0-9]*`
`.[0-9,0-9]+`

Looking at all these variants though, maybe there are just too many to safely protect against? But maybe there's a way?

**Comment by respawner** [comment]
Indeed you are quite right. Submitting this kind of commands several could be quite CPU consuming especially for small routers.

Any other thoughts about regexp that we should not allow?

**Comment by jlixfeld** [comment]
Thinking about this further, perhaps make the filter a config option instead?  This would let a user specify what ever regexp(s) they do not want accepted.

**Comment by respawner** [comment]
Good idea. Lets do it in this way.

We will pre-populate some defaults and let users complete them (or totally overwrite them at their own risks).
