### ISSUE TITLE
ubiquiti routers

### ISSUE THREAD

**Issue by Wqrld** [respawner/looking-glass#62]
Would i be able to use this with a ubiquiti router?

**Comment by respawner** [comment]
There is no support for Ubiquiti router yet, but I'll be glad to accept any PR implementing it. If nobody can contribute to the code directly, I can try implementing it myself but I'll need guidance regarding the commands to be used.

**Comment by Wqrld** [comment]
> There is no support for Ubiquiti router yet, but I'll be glad to accept any PR implementing it. If nobody can contribute to the code directly, I can try implementing it myself but I'll need guidance regarding the commands to be used.

Wouldn't this be the same as EdgeOS? `EdgeOS is a fork of Vyatta developed by Ubiquiti Networks. `

**Comment by respawner** [comment]
Indeed, we do have a bit of [documentation](https://looking-glass.readthedocs.io/en/latest/vyatta/) about EdgeOS and stuff.
