### ISSUE TITLE
Ssh to windows Server

### ISSUE THREAD

**Issue by koriks1111** [respawner/looking-glass#63]
_Hi_

im new in terms of using looking glass. this is my concern. i have windows server 2016 since no more telnet server features on windows 2016 server i have installed 3rd party Ssh for the machine. 

but when my looking glass machine calling the windows server thru ssh seems not working and no output also in web interface. 

not sure if i explain it well. 

here is the config. 
<Router Name="Router1" OSType = "windows">
                        <URL>ssh://lg:password@mydomain.com</URL>
                </Router>

**Comment by koriks1111** [comment]
![image](https://user-images.githubusercontent.com/42999735/54668751-9b6f8f00-4b2a-11e9-97ce-41552c4d028d.png)

**Comment by respawner** [comment]
I actually don't know about Windows SSH but the looking glass does not really care about the SSH server it connects to.

This code works in a pretty simple way:

1. Connect to a host using SSH
2. Send commands to the host through the SSH pipe
3. Get the result of these commands

Any SSH servers should be OK with that.

That said I'm not sure about what you are trying to achieve here. Do you have a compatible router running on Windows?

**Comment by koriks1111** [comment]
no router on my windows server. and i can confirmed that i can ssh from my looking glass machine going to the windows machine but not via LG config. 


tcpping to port 23 is open.

**Comment by respawner** [comment]
I don't have the full picture here but what's the point of having the looking glass trying to connect to your Windows Server machine if you don't run any software router on it?

Is the port 22 opened (for TCP)?

**Comment by koriks1111** [comment]
yes, tcp port 22 is open. 

i want to use ssh to connect to my windows server command line and run diff kind of command, ping, tracert something. 

i can ssh from lg server to windows server manually. but when i run the thru looking glass web gui it's no output.. 

![image](https://user-images.githubusercontent.com/42999735/54688875-76dedb80-4b59-11e9-8e1d-63e24097c792.png)


![image](https://user-images.githubusercontent.com/42999735/54689026-b3aad280-4b59-11e9-8be8-6d3b51e2a4e6.png)

**Comment by koriks1111** [comment]
to show that port 22 is open

![image](https://user-images.githubusercontent.com/42999735/54689465-8d396700-4b5a-11e9-8e68-84972f43d53c.png)

**Comment by respawner** [comment]
This code does not support Windows so you'll not be able to achieve want to you want to. You can turn on debug though, see [[1]](https://looking-glass.readthedocs.io/en/latest/configuration/).

Looking back at your first reply, looks like you're doing some config in XML. This project does not deal with XML for the configuration part. Are you sure you're in the right place? :)
