### ISSUE TITLE
Add parameter to permit route lookup only within bounded prefix length

### ISSUE THREAD

**Issue by fstolba** [respawner/looking-glass#69]
Hi,

first off, thank you for this wonderful project!

At the moment, it's possible to request the route for 100.0.0.0/1 which results in very large output and high load on the devices while providing very little value for actual troubleshooting. I would therefore like to propose the addition of a parameter which sets a lower bound on the prefix length being permitted.

Example: 
Add following in config.php ```$config['misc']['minimum_prefix_length'] = 16;```.
When set, only permit 10.0.0.0/x as input for the command show route when 16 ≤ x ≤ 32.
Else display an error message.

Let me know what you think.

**Comment by respawner** [comment]
Looks easy to implement. I agree it can be useful for router with small control plane.

**Comment by fstolba** [comment]
Thank you for taking the time and putting in the effort for implementing this feature, it is very much appreciated.
