### ISSUE TITLE
Cannot connect the router

### ISSUE THREAD

**Issue by simonluson** [respawner/looking-glass#70]
After selected a router and command , input a parameter ,press input ,it's warning “Error! Cannot connect to the router!!!”  I can login the router on lookingglass server .

**Comment by respawner** [comment]
You need to be more specific about what you are using:
1. router platform?
2. authentication mechanism?

**Comment by simonluson** [comment]
1. both cisco 7609 and juniper mx960
2. ssh 
It's very strange that it's work very well a few  days ago .But I do not know why suddenly it is not work.

**Comment by respawner** [comment]
I suggest to turn on the auth debug with `$config['logs']['auth_debug'] = true;`. Then check the log file.

**Comment by simonluson** [comment]
Here are logs:
May  9 19:10:59 localhost httpd: PHP Notice:  Cannot connect to 192.168.1.100:22. Error 13. Permission denied in /var/www/html/looking-glass/libs/phpseclib-1.0.9/Net/SSH2.php on line 1157

**Comment by respawner** [comment]
You could have some issues due to access permissions maybe?

**Comment by simonluson** [comment]
the answer is SELINUX=disabled

**Comment by hendranata** [comment]
> Here are logs:
> May 9 19:10:59 localhost httpd: PHP Notice: Cannot connect to 192.168.1.100:22. Error 13. Permission denied in /var/www/html/looking-glass/libs/phpseclib-1.0.9/Net/SSH2.php on line 1157
> I configured $config['logs']['file'] = '/var/log/looking-glass.log'; . But there is no entry in looking-glass.log

same.. i cant find /var/log/looking-glass.log
where do u get the log location?
