### ISSUE TITLE
Broken command building mechanism

### ISSUE THREAD

**Issue by InsaneSplash** [respawner/looking-glass#74]
When using FRRouting/Quagga, I am finding that the command is being built incorrectly. It seems that the 'vytsh -c' command is being prepended to each part of the command line being built.

example:
> % Unknown command: vtysh -cshow bgpvtysh -cipv4vtysh -c1.1.1.1vtysh -c

As of this post, I am using the latest version available through github.

**Comment by respawner** [comment]
This is indeed an issue that appeared recently and it's not limited to FRR. It has an impact on all supported platform. I think it has been introduced by f3beaff.

**Comment by InsaneSplash** [comment]
Thanks for the quick response. If you require any further testing or information, please let me know.
