### ISSUE TITLE
Issues Connecting to Cisco Switch

### ISSUE THREAD

**Issue by hammons0212** [respawner/looking-glass#75]
Good Day!

Allow me to first start off by saying thanks for creating looking glass software and still actively working on it! We are currently using one that hasn't been updated in like 10 years, and we are looking for an alternative. Also, I've followed the guides in the /docs directory.

I have a Cisco switch (I forget the platform - non catalyst 3850 I think) that I am trying to test out before deploying for one of our bigger customers. Anywho, I'm trying to get SSH to work with the switch, but when I try to ping from the web interface, I just get an error (red bar across the screen that just says "Error!". Note the info below.

Router config:
`
// Authentication based on SSH or Telnet with password

$config['routers']['router1']['host'] = 'ip.v4.add.ress';
$config['routers']['router1']['user'] = 'sshuser';
$config['routers']['router1']['pass'] = 'sshuserpassword';
$config['routers']['router1']['auth'] = 'ssh-password';
$config['routers']['router1']['type'] = 'cisco';
$config['routers']['router1']['desc'] = 'S1SW01';
$config['routers']['router1']['source-interface-id'] = 'vlanXX';
$config['routers']['router1']['source-interface-id']['ipv4'] = 'vlan.xx.ip.addr';
$config['routers']['router1']['disable_ipv6'] = false;
$config['routers']['router1']['disable_ipv4'] = false;
$config['routers']['router1']['timeout'] = 30;
`

I also enabled logging, but so far that file has been empty. Note the logs below from /var/log/httpd/error_log

`
[Thu Jun 13 10:33:14.006941 2019] [:error] [pid 15672] [client my.ip.addr.ess:22818] PHP Warning:  Illegal string offset 'ipv4' in /var/www/html/looking-glass/config.php on line 45, referer: http://lg.server.ip.addr/looking-glass/ 

Above error is the source interface id ipv4 configuration.

[Thu Jun 13 10:33:14.007649 2019] [:error] [pid 15672] [client my.ip.addr.ess:22818] PHP Parse error:  syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE) in /var/www/html/looking-glass/includes/command_builder.php on line 50, referer: http://lg.server.ip.addr/looking-glass/

The above error is in reference to this config in that file: public function add(...$elements) {
`
I'm running the LG software on a CentOS 7 VM if that helps any. Also, I got software via the "git" command, and just moved that folder to /var/www/html. Any assistance would be greatly appreciated.

![error](https://user-images.githubusercontent.com/51793666/59446366-5f696480-8dcf-11e9-901f-59c5f12b1e5b.PNG)

**Comment by hammons0212** [comment]
Apologies for the double post, but I removed the "..." from the error line above, and now I'm getting this error:

`
[Thu Jun 13 12:23:30.784113 2019] [:error] [pid 15662] [client my.laptop.ip.addr:25348] PHP Parse error:  syntax error, unexpected '->' (T_OBJECT_OPERATOR) in /var/www/html/routers/cisco.php on line 49, referer: http://lg.server.ip.addr/
`

Don't know if that helps.

**Comment by respawner** [comment]
Looks like it's an issue with the PHP version that you are using with your web server. Can you please tell us which one is it? Note that this code will only work with version greater than 7.0.

Also if you use:
```php
$config['routers']['router1']['source-interface-id'] = 'vlanXX';
```

You should not use:
```php
$config['routers']['router1']['source-interface-id']['ipv4'] = 'vlan.xx.ip.addr';
```

It's one line or the other.

**Comment by hammons0212** [comment]
Thanks for the quick reply! I'm using PHP 7.0:

`
PHP 7.0.33 (cli) (built: May 28 2019 09:26:45) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.33, Copyright (c) 1999-2017, by Zend Technologies
`

I'll tweak the config and see if that works. Also, I'll see if I can get PHP to 7.2 to see if that helps.

**Comment by hammons0212** [comment]
So, I must have not rebooted after updating to PHP code v7 (I was on 5.4 - which is what comes in the default CentOS repos). Anywho, I got working. Thanks for helping me out!
