### ISSUE TITLE
Tweak Command Output

### ISSUE THREAD

**Issue by hammons0212** [respawner/looking-glass#76]
I was able to get the application talking with our BGP routers, and everything is looking good. I just had a question about tweaking the commands that are issued to the routers. We don't want the output to display interface information, which is the case for a few of the outputs. This is specifically for Junipers. We would like to pipe the command to exclude interface info. Example:

show route 8.8.8.8 protocol bgp table inet.0 | except "via"

Is this a simple tweak? Any help would be greatly appreciated.

**Comment by respawner** [comment]
If you just want to exclude some line from the output you can use the `filters` configuration stanza like so:

```php
$config['filters']['output'][] = '/via/';
```

Otherwise you'll have to change the code in one of the router classes, `routers/juniper.php` in your case.

**Comment by hammons0212** [comment]
That did the trick! Thanks for the help!
