### ISSUE TITLE
RouterOS Mikrotik - Source interface selection and IPv4 and IPv6 parameters.

### ISSUE THREAD

**Issue by rfminelli** [respawner/looking-glass#83]
Source interface selection and ipv4 and ipv6 parameters are not working on RouterOS (Mikrotik).
Version:  Looking Glass 2.0.1

**Comment by respawner** [comment]
This is supposed to be working for `ping` and `traceroute` although I don't have a device to test this.

Can you paste the relevant config and give the command the looking glass is trying to execute?

**Comment by rfminelli** [comment]
It could be for these errors:
Warning: Illegal string offset 'ipv4' in /var/www/vhosts/xxxx.com.br/public_html/lg/config.php on line 62
Warning: Illegal string offset 'ipv6' in /var/www/vhosts/xxxx.com.br/public_html/lg/config.php on line 63

When I activate these 3 lines it is displayed:
// The router source interface to be used
$ config ['routers'] ['router1'] ['source-interface-id'] = 'Loopback';
$ config ['routers'] ['router1'] ['source-interface-id'] ['ipv4'] = '1xx.xx.xx.2xx';
$ config ['routers'] ['router1'] ['source-interface-id'] ['ipv6'] = '2xxx:xxxx:xxxx:xxxx:xxxx:xxxx: xxxx:xxxx';

I am using PHP:
PHP 7.1.17-0ubuntu0.17.10.1 (cli) (built: May  9 2018 17:28:01) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.17-0ubuntu0.17.10.1, Copyright (c) 1999-2018, by Zend Technologies

**Comment by respawner** [comment]
There is an issue in your configuration.

Either you use the following:
```
$config['routers']['router1']['source-interface-id'] = 'Loopback';
```

Or the other two lines:
```
$config['routers']['router1']['source-interface-id']['ipv4'] = '1xx.xx.xx.2xx';
$config['routers']['router1']['source-interface-id']['ipv6'] = '2xxx:xxxx:xxxx:xxxx:xxxx:xxxx: xxxx:xxxx';
```
