### ISSUE TITLE
[Are you a robot?] Google reCaptcha will fail when hosted behind rev-proxy

### ISSUE THREAD

**Issue by rabin-io** [respawner/looking-glass#96]
When the `HTTP_X_FORWARDED_FOR` variable is set is can contain a chain of proxy servers which the request passed to get to the server, this result that the variable `$requester` can have a value like "8.8.8.8, 192.168.0.1" which is directly passed to Google recaptcha validation API, and will always fail.
not to mention that that header can be set by the user, and we trust it directly in the code.

```php
// From where the user *really* comes from.
if (isset($_SERVER['HTTP_X_FORWARDED_FOR'])) {
  $requester = $_SERVER['HTTP_X_FORWARDED_FOR'];
} else {
  $requester = $_SERVER['REMOTE_ADDR'];
}
```

In my environments I always overwrite this header with the REMOTE_ADDR, as you can never trust the user input.

**Comment by respawner** [comment]
Do you have a solution in mind for this issue?

**Comment by rabin-io** [comment]
As I mention above, in our deployment I always overwrite the `HTTP_X_FORWARDED_FOR` with the `REMOTE_ADDR`.

Another option is to split the string by `,` and pass only the last IP. 

But because  this header is spoof-able, I would recommended disableing it by default, and let the user how deploy the application the choice to supprt it if he like so.

**Comment by respawner** [comment]
Both of these solutions look fair to me. It's, IMHO, a simple issue so, if someone is willing to make a fix for it I'll be happy to review and merge it.

**Comment by rabin-io** [comment]
I sent a PR with my changes to fix this issue, and disable the use of `HTTP_X_FORWARDED_FOR` by default as it safer.

Let me know what do you think.
